baseURL = 'https://vault.nickbanning.com'
languageCode = 'en-us'
title = 'mental excess.'
theme = 'gokarna'
enableRobotsTXT = true
enableEmoji = true

[menu]
  [[menu.main]]
  identifier = "posts"
  url = "/posts/"
  name = "Vault"
  weight = 1

  [[menu.main]]
    identifier = "tags"
    url = "/tags/"
    name = "Tags"
    weight = 2

[params]
  avatarURL = "/images/light.jpg"
  avatarSize = "size-l"
  description = "- my creative repository -"
  accentColor = "#6495ED"
  metaKeywords = ["", "", ""]
  showPostsOnHomePage = "recent"
  footer = "nick."
  togglePreviousAndNextButtons = "true"
