baseURL = 'https://vault.nickbanning.com/'
languageCode = 'en-us'
title = 'mental excess.'
theme = 'gokarna'
enableRobotsTXT = true
enableEmoji = true
enableInlineShortcodes = true


[menu]
  [[menu.main]]
  identifier = "posts"
  url = "/posts/"
  name = "Vault"
  weight = 1
  pre = "<img class='svg-inject' src='/icons/bookmark.svg' />"

  [[menu.main]]
    identifier = "tags"
    url = "/tags/"
    name = "Tags"
    weight = 2
    pre = "<img class='svg-inject' src='/icons/tag.svg' />"

[params]
  avatarURL = "/images/light.jpg"
  avatarSize = "size-l"
  description = "- my creative repository -"
  accentColor = "#6495ED"
  metaKeywords = ["", "", ""]
  showPostsOnHomePage = "recent"
  footer = "nick."
  togglePreviousAndNextButtons = "true"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[markup.goldmark.renderer]
  unsafe = true
